# Generated by Django 2.2.2 on 2020-05-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200511_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pin',
            field=models.CharField(max_length=10),
        ),
    ]
