# Generated by Django 2.2.2 on 2020-05-19 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_signup'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('username', models.CharField(default='', max_length=30, primary_key='true', serialize=False)),
                ('phone', models.CharField(default='', max_length=10)),
                ('add', models.TextField(default='', max_length=500)),
                ('state', models.CharField(default='', max_length=20)),
                ('city', models.CharField(default='', max_length=20)),
                ('pin', models.CharField(default='', max_length=10)),
            ],
        ),
    ]
