# Generated by Django 2.2.2 on 2020-05-19 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_userdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='userimage',
            field=models.ImageField(default='/static/shop/icons/user.png', upload_to='shop/images'),
        ),
    ]
