# Generated by Django 2.2.2 on 2020-05-20 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_userdetail_userimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='userimage',
            field=models.ImageField(default='', upload_to='shop/images'),
        ),
    ]
