# Generated by Django 2.2.2 on 2020-05-20 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20200520_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='userimage',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
