# Generated by Django 2.2.2 on 2020-05-20 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20200520_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='userimage',
            field=models.ImageField(default='/static/shop/icons/user.png', upload_to='userimage'),
        ),
    ]
