# Generated by Django 2.2.2 on 2020-05-22 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20200520_1158'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SignUp',
        ),
    ]
